"""Mocks for vertexai.language_models.TextEmbeddingModel and GenerativeModel.

These mimic the real Vertex AI SDK shape so swapping in production is a one-line change.
"""
from dataclasses import dataclass
from typing import Any
import hashlib
import numpy as np


@dataclass
class TextEmbedding:
    """Mirrors vertexai.language_models.TextEmbedding return shape."""
    values: list[float]
    statistics: dict[str, Any] | None = None


class MockTextEmbeddingModel:
    """Mocks vertexai.language_models.TextEmbeddingModel.

    Real usage:
        from vertexai.language_models import TextEmbeddingModel
        model = TextEmbeddingModel.from_pretrained("textembedding-gecko@003")
        embeddings = model.get_embeddings(["hello"])
    """
    def __init__(self, model_name: str = "textembedding-gecko@003", dim: int = 384):
        self.model_name = model_name
        self.dim = dim

    @classmethod
    def from_pretrained(cls, model_name: str) -> "MockTextEmbeddingModel":
        return cls(model_name=model_name)

    def get_embeddings(self, texts: list[str]) -> list[TextEmbedding]:
        out = []
        for t in texts:
            rng = np.random.RandomState(int(hashlib.md5(t.encode()).hexdigest()[:8], 16))
            v = rng.normal(0, 1, self.dim).astype(np.float32)
            v = v / (np.linalg.norm(v) + 1e-9)
            out.append(TextEmbedding(values=v.tolist(),
                                     statistics={"token_count": len(t.split())}))
        return out


@dataclass
class GenerationResponse:
    text: str
    usage_metadata: dict[str, int] | None = None


class MockGenerativeModel:
    """Mocks vertexai.generative_models.GenerativeModel.

    Real usage:
        from vertexai.generative_models import GenerativeModel
        model = GenerativeModel("gemini-1.5-flash")
        resp = model.generate_content("rewrite this query: ...")
    """
    EXPANSIONS = {
        "peak load": "system scalability under high traffic concurrent users autoscaling capacity",
        "too many users": "high concurrency peak load throttling rate limiting saturation",
        "failover": "disaster recovery failover redundancy outage downtime replica promotion",
        "outage": "downtime failover disaster recovery incident response runbook",
        "api": "endpoint rate limit throttle quota request",
        "cache": "redis cdn ttl eviction layer",
        "security": "zero-trust mtls waf ddos authentication",
    }

    def __init__(self, model_name: str = "gemini-1.5-flash"):
        self.model_name = model_name
        self.model = model_name  # alias for ILLM-style consumers

    def generate_content(self, prompt: str, **kwargs) -> GenerationResponse:
        prompt_lower = prompt.lower()

        if "rewrite" in prompt_lower or "expand" in prompt_lower:
            expansions = [exp for kw, exp in self.EXPANSIONS.items() if kw in prompt_lower]
            extra = " ".join(expansions) if expansions else "system architecture infrastructure"
            text = f"{prompt.split(':')[-1].strip()} {extra}"
            return GenerationResponse(
                text=text,
                usage_metadata={"prompt_token_count": len(prompt.split()),
                                "candidates_token_count": len(text.split())},
            )

        if "answer" in prompt_lower or "context:" in prompt_lower:
            ctx_start = prompt.lower().find("context:")
            q_start = prompt.lower().find("question:")
            question = prompt[q_start + 9:].strip() if q_start > -1 else "your question"
            context_snippet = ""
            if ctx_start > -1 and q_start > ctx_start:
                ctx = prompt[ctx_start + 8:q_start].strip()
                first_chunk = ctx.split("---")[0].strip() if "---" in ctx else ctx[:300]
                context_snippet = first_chunk[:280]

            text = (
                f"Based on the retrieved context, here is the answer to: \"{question}\"\n\n"
                f"{context_snippet}\n\n"
                f"(Generated by mocked GenerativeModel — replace with real Vertex AI Gemini in production.)"
            )
            return GenerationResponse(
                text=text,
                usage_metadata={"prompt_token_count": len(prompt.split()),
                                "candidates_token_count": len(text.split())},
            )

        return GenerationResponse(text="[mock response]",
                                  usage_metadata={"prompt_token_count": 0,
                                                  "candidates_token_count": 2})
